apiVersion: v1
kind: Service
metadata:
  name: tethys-lb
  namespace: tethys
  labels:
    name: tethys-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tethys-github
