apiVersion: v1
kind: Service
metadata:
  name: tethys-ers-ce-lb
  namespace: tethys
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    name: tethys-ers-ce-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: ers-ce
