apiVersion: v1
kind: Service
metadata:
  name: tethys-github-lb
  namespace: tethys
  annotations:
    # service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.208.1.101 # does not work in RDE
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    name: tethys-github-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: tethys-github
