apiVersion: v1
kind: ConfigMap
metadata:
  name: tethys-pg-config
  namespace: tethys
  labels:
    app: tethys-pg
data:
  # POSTGRES_DB: tethys_platform
  # POSTGRES_USER: tethys_default 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pass 
  POSTGRES_HOST_AUTH_METHOD: trust
