apiVersion: v1
kind: Service
metadata:
  name: tethys-lb
spec:
  type: LoadBalancer
  selector:
    app: tethys
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalTrafficPolicy: Local
