# 1st create volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tethys-postgres-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity: 
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/volume/tethys"
---

# 2nd create volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tethys-postgres-data-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
