apiVersion: v1
kind: Service
metadata:
  name: hello-nginx
spec:
  # type: NodePort
  selector:
    app: hello-nginx
  ports:
  - port: 8050
    # targetPort: 80
    # nodePort: 30002
    #name: hello-nginx-port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-vol
data:
  nginx.conf: '
events {
}
http {
   server {
       listen 80;
       location / {
           return 200 "Hello world!";
       }
   }
}
'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx-dep
  labels:
    app: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
      - name: hello-nginx-app
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
          - name: config-vol
            mountPath: /etc/nginx/
      volumes:
        - name: config-vol
          configMap:
            name: nginx-config-vol
            items:
              - key: nginx.conf
                path: nginx.conf
        # envFrom:
        #   - configMapRef:
        #       name: nginx-config
